# Generated by Django 3.1.6 on 2021-12-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugtest',
            name='labID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sensordetails',
            name='sDepartment',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sensordetails',
            name='sFloor',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sensordetails',
            name='sRoom',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='sTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
